### ISSUE TITLE
Project Permission Keys

### ISSUE THREAD

**Issue by AntoineDao** [speckleworks/SpeckleServer#132]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
I expect the project permissions to be either nested in the `permissions` key or not nested in in but not both. This is confusing me when adding and upgrading users.

#### Actual Behaviour
Permissions are saved both under `permissons` key and not for `canRead` but only nested under `permissions` for `canWrite`:

```json
{
  "success": true,
  "resource": {
    "permissions": {
      "canRead": [
        "5cf3921f777d5400112368a6"
      ],
      "canWrite": [
        "5cf3921f777d5400112368a6"
      ]
    },
    "private": true,
    "canRead": [
      "5cf3921f777d5400112368a6"
    ],
    "canWrite": [],
    "anonymousComments": false,
    "comments": [],
    "name": "test project",
    "description": "a project made for testing purposes",
    "tags": [],
    "streams": [
      "R1N0NWivG"
    ],
    "deleted": false,
    "_id": "5cf3921f4a8f200010391492",
    "owner": "5cf3921d4a8f20001039148d",
    "createdAt": "2019-06-02T09:08:47.564Z",
    "updatedAt": "2019-06-02T09:08:48.121Z",
    "__v": 3
  }
}
```

#### Affected Projects
Making it confusing and needlessly difficult to configure the python sdk.

#### Proposed Solution (if any)
Stick to the not nested version outside of the `permissions` key as that is how `stream` permissions are managed.

**Comment by didimitrie** [comment]
I know it's a bit of a complex problem down on the project permission settings. Main issue with it, and also the reason why things are complicated, is because as user you can have read/write access to the `project` resource itself. 

ie,
-  **read** permissions will pretty much allow you to see this in your "feed", but **write** permissions will actually allow you to add/remove users and streams from this project. So read = project member, whereas write = project manager kind of situation. 
- a user with **read** permissions on a project can have **write** permissions to the streams. 

Nevertheless, as far as I know, the backend should take care of all these extra jazz if you just hit the endpoints. Potentially, to sync with the local state in python, would just retrieving the project (and/or streams) from the API would work? Albeit not really elegant, but hey...

**Comment by AntoineDao** [comment]
Question tag is the correct one to add indeed. If there is a reason for this then it's grand (I'm not one to discuss the logic of the server!). Just wanted to make sure I wasn't handling oddly duplicated information with the client 😄
