### ISSUE TITLE
JN validation - admin choice (no validation, regex, or a list that can be updated by a third part service).

### ISSUE THREAD

**Issue by daviddekoning** [speckleworks/SpeckleServer#172]
Dim's notes:
(3/10/19) I have requested access to the ADS api to be able to properly dredge the JNs and populate said list. Nevertheless, this will mean:
- server needs to authenticate against ADS; this entails extra config on deployment and extra secrets int environment vars
- alternatively, the end-user authenticates against ADS, but this opens up tons of new caveats for the admin ui (not keen)

(2010/12/02) Let full project number validation be implemented as a plugin (i.e. don't have the above list option, let the plugin take care of it)

**Comment by mswaidan** [comment]
General question that comes out of this issue: how should server side extensions that may be company / server specific be integrated? Right now we're just running a separate node.js program that calls our JN API & then checks the results against our SpeckleServer's projects list using the SpeckleServer projects API. _Should_ these things be integrated into SpeckleServer, just run alongside?

**Comment by daviddekoning** [comment]
It's still an open question. My original thought was to simply have a list in the speckleserver that can be updated by third-party services. That way you can write code that accesses your org's data and periodically writes a list of valid job numbers to your server.

However, your custom plugin presentation last week looked a lot more graceful and flexible. If we added a validation hook to speckleserver that a plugin could connect to, then we would both simplify the server code, and provide individual orgs a more flexible solution.

What are your thoughts @mswaidan @didimitrie ?

**Comment by didimitrie** [comment]
Was thinking via a plugin once https://github.com/speckleworks/SpeckleAdmin/pull/89 is merged. Nevertheless, this will cut off any possibility of allowing these to be set directly from the app clients; which for me it's fine as it's less ui work that "ain't nobody have time to support that". 

Overall, there's actually a larger discussion at hand here that I didn't have time to dwell or think through properly, nevertheless it boils down to having tags live separately in the db (a la github), so that one tag can be applied/enforced on multiple streams, projects; global tags per server (ie, job numbers). We'll park this for now. 

@mswaidan, any timeline on the plugins PR? I can wrap it up if you let me know what's missing, etc. Wanted to merge it then and there so you could present it live at the meetup, but you did anyway :D

**Comment by mswaidan** [comment]
I made a few tweaks to the Navbar UI (nest plugin routes under a 'Plugins'
group). Will push those later today. Other than that I think it's good to
go, just needs documentation.

**Comment by daviddekoning** [comment]
The speckle server now has mask validation as a basic option, and the new dynamic plugin architecture will allow firms to add validators that connect directly to their own project management systems.
